# 开发环境配置
spring:
  profiles:
    active: dev
  
  # 开发环境数据源
  datasource:
    url: jdbc:h2:mem:devdb
    hikari:
      maximum-pool-size: 5
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# 服务器配置
server:
  port: 8080

# 日志配置
logging:
  level:
    root: DEBUG
    com.example.agent: DEBUG
    org.springframework.ai: DEBUG

# Agent配置
agent:
  knowledge:
    vector-store:
      enabled: true
    sql-database:
      enabled: true
    api-source:
      enabled: true
  pipeline:
    async: true
  mcp:
    enabled: true 